version: '3.8'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - MONGO_URI=mongodb+srv://abhay:CDHwMuuaJ2JhKEkl@cluster0.g6clnyx.mongodb.net/galaxeye
      - PORT=5000
    depends_on:
      - mongo

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    stdin_open: true

  mongo:
    image: mongo
    ports:
      - "27017:27017"
